### ISSUE TITLE
PyQt导入问题

### ISSUE THREAD

**Issue by Iron-monkey** [yifer97/ghs-translator#1]
![image](https://user-images.githubusercontent.com/52274225/85367351-a8640500-b55b-11ea-8352-0bcd2204bca1.png)

**Comment by yifer97** [comment]
这个应该不是我程序的问题，我帮你查了下，可能是包名称冲突；
我这里给的建议是conda建立一个新的虚拟环境，然后重新安装(`pip install`)，默认最新版就可以
```
pyqt5
PyQtWebEngine
googletrans==2.4
```
详细的文档coming soon...
如果以上还没解决的话，继续issue
